# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cf0712cd8e4e71b5f73c727840ac3e9077713fe14a93fddd4371d0703924d8cb37d3f1c7037141375505d0c77be5c4e817a400b852ebc342cbf6a9c0e006ff3c

test:
  secret_key_base: 4eca7c85ef8ff18d036206c175d28cd0880dc4590f626e873d5f9e3b0cc0c54823d4bfcc57f36b34cd8da55bcf6fd6120cca85a1af189e742c7197b40cfd3478

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
